# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: ngs-qc-1.7
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::cutadapt=4.1
  - bioconda::bioconductor-dada2=1.22.0
  - bioconda::bioconductor-shortread=1.52.0
  - bioconda::bwa=0.7.17
  - bioconda::samtools=1.13
