title: "NGS QC Report"
subtitle: "QC Report for Illumina sequencing"
custom_logo: "ikmblogo.png"
custom_logo_title: "Competence Centre for Genomic Analysis (CCGA), Kiel"
custom_logo_url: "http://www.ccga.uni-kiel.de"

extra_fn_clean_exts:
    - "_001_"

report_comment: >
    This report has been generated automatically by the CCGA QC pipeline.

report_header_info:
    - Contact E-mail: "ccga@ikmb.uni-kiel.de"
    - Application Type: "QC"

top_modules:
    - 'general_stats'
