title: "NGS QC report"
subtitle: "QC report for sequencing run"
custom_logo: "ikmblogo.png"
custom_logo_title: "Insitute of Clinical Molecular Biology, Kiel"
custom_logo_url: "http://www.ikmb.uni-kiel.de"

extra_fn_clean_exts:
    - _001

report_header_info:
    - Contact E-mail: "ccga@ikmb.uni-kiel.de"
    - Application Type: "QC"
